<a href="https://colab.research.google.com/github/BNavya1995/Handling_messy_data/blob/main/Handling_messy_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [42]:
df['age']=df['age'].fillna(df['age'].median())
df['age']

0    25.0
1    35.0
2    35.0
3    35.0
4    35.0
5    40.0
Name: age, dtype: float64

In [43]:
df['city']=df['city'].fillna(df['city'].mode()[0])
df['city']

0    Mumbai
1     Delhi
2     Delhi
3    Mumbai
4     Delhi
5     Delhi
Name: city, dtype: object

In [44]:
df=df.drop_duplicates()
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0   Delhi    Male          95000

In [45]:
from sklearn.preprocessing import LabelEncoder
if 'city' in df.columns:
   df=pd.get_dummies(df,columns=['city'],prefix='city',dtype = int)
if 'gender' in df.columns:
  le=LabelEncoder()
  df['gender']=le.fit_transform(df['gender'])
print(df)

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000           0            1
1            2  35.0       0          80000           1            0
2            3  35.0       0          60000           1            0
3            4  35.0       1         120000           0            1
5            5  40.0       1          95000           1            0

age---- max = 40, min = 25

annual income=std =30903

In [52]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler_minmax=MinMaxScaler()
scaler_standard=StandardScaler()
num_col=['age','annual_income']

df_minmax=df.copy()
df_minmax[num_col]=scaler_minmax.fit_transform(df[num_col])
print("Min-Max Scaled DataFrame:\n ",df_minmax,"\n")

df_standard=df.copy()
df_standard[num_col]=scaler_standard.fit_transform(df[num_col])
print("Standarization Dataframe:\n",df_standard)

Min-Max Scaled DataFrame:
     customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000           0            1
1            2  0.666667       0         0.5000           1            0
2            3  0.666667       0         0.2500           1            0
3            4  0.666667       1         1.0000           0            1
5            5  1.000000       1         0.6875           1            0

Standarization Dataframe:
    customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -1.837117       1      -1.410970           0            1
1            2  0.204124       0       0.036179           1            0
2            3  0.204124       0      -0.687396           1            0
3            4  0.204124       1       1.483328           0            1
5            5  1.224745       1       0.578860           1            0

min-max Scaling is used for distance based models.
Standarization used for linear regression